/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Stoinercraft (https://sketchfab.com/furkanshieldd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/electro-guitar-57f8d70a8f1b4a2f9aed9ecc96c795e1
Title: Electro Guitar
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')


rembrandt

city
Made by @NikkitaFTW & contributors inspired by the gltfjsx cli

